name = "StructIO"
uuid = "53d494c1-5632-5724-8f4c-31dff12d585f"
version = "0.3.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[targets]
test = ["Test", "REPL"]
